import { GoogleGenAI } from "@google/genai";
import { Message, Role, AuditMetadata } from "../types";

export interface StreamChunk {
  text: string;
  done: boolean;
  audit?: AuditMetadata;
}

const sleep = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));

function buildAudit(ref: string, currentMetrics?: any, violations: string[] = []): AuditMetadata {
  return {
    module_id: "MKone-CFR-01",
    assumptions: [
      "Browser deployment may not have a configured Gemini API key.",
      "Declared telemetry is treated as simulated unless a verified source is connected."
    ],
    constraints_checked: [
      "A1 traceability",
      "A2 consistency",
      "A3 robustness",
      "No secret/API-key request through chat"
    ],
    violations,
    confidence: violations.length ? 0.72 : 0.86,
    refs: [ref],
    telemetry_snapshot: currentMetrics
      ? {
          gamma_hz: currentMetrics.gamma ?? 0,
          vireax_v: currentMetrics.vireax ?? 0,
          drift_seconds: currentMetrics.drift ?? 0,
          error_epsilon: currentMetrics.error ?? 0,
        }
      : undefined,
  };
}

function offlineResponse(prompt: string, currentMetrics?: any): { text: string; audit: AuditMetadata } {
  const p = prompt.trim().toLowerCase();

  if (p.includes("status") || p.includes("/status")) {
    return {
      text: `MIRRORME STATUS\n\nRuntime: ONLINE (browser demo)\nMode: OFFLINE-FIRST / STATIC DEPLOYMENT\nBackend model: not connected in this deployment\nDatabase: not connected\nAudit chain: simulated client-side only\nMemory: current session only\nNetwork: static GitHub Pages host\n\nTelemetry shown in the dashboard is generated by the local simulator and should be treated as simulated, not measured biological or hardware telemetry.`,
      audit: buildAudit("OFFLINE_STATUS", currentMetrics),
    };
  }

  if (p.includes("contradiction") || p.includes("swans") || p.includes("p and not-p")) {
    return {
      text: `Contradiction trap result: under classical logic, asserting P and not-P in the same scope produces inconsistency.\n\nMinimal repair options:\n1. Revise the weaker premise.\n2. Scope one premise to a narrower context or time.\n3. Store both in paraconsistent mode and block arbitrary inference.\n\nFor the swan case: \"All swans are white\" conflicts with \"a black swan exists\". The minimal correction is \"Most observed swans in the dataset are white\" or \"normally swans are white, with exceptions.\"`,
      audit: buildAudit("OFFLINE_CONTRADICTION_TRAP", currentMetrics),
    };
  }

  if (p.includes("gate") || p.includes("go/no-go") || p.includes("vireax")) {
    const v = currentMetrics?.vireax ?? null;
    const drift = currentMetrics?.drift ?? null;
    const eps = currentMetrics?.error ?? null;
    const psi = currentMetrics?.psi ?? null;
    const go = v !== null && drift !== null && eps !== null && psi !== null && v >= 0.99 && drift <= 0.00001 && eps <= 0.05 && psi >= 0.995;
    return {
      text: `Orchestration gate check:\n\nGO = (v >= 0.99) AND (drift <= 0.00001s) AND (epsilon <= 0.05) AND (psi >= 0.995)\n\nCurrent simulated frame:\n- v: ${v ?? "unavailable"}\n- drift_s: ${drift ?? "unavailable"}\n- epsilon: ${eps ?? "unavailable"}\n- psi: ${psi ?? "unavailable"}\n\nVerdict: ${go ? "GO candidate. Requires 5 consecutive passing frames." : "NO-GO or insufficient verified telemetry."}`,
      audit: buildAudit("OFFLINE_GATE_CHECK", currentMetrics),
    };
  }

  return {
    text: `MirrorMe offline auditor response.\n\nI can inspect logic, arithmetic, telemetry thresholds, contradiction traps, and MirrorMe/MKone architecture from this static deployment. No external AI model is connected here unless a Gemini API key is configured at build time.\n\nYour input was accepted as a declared artifact, not independently verified.`,
    audit: buildAudit("OFFLINE_DEFAULT_RESPONSE", currentMetrics),
  };
}

async function* streamText(text: string, audit: AuditMetadata): AsyncGenerator<StreamChunk> {
  const chunks = text.match(/.{1,48}(\s|$)/g) ?? [text];
  for (const chunk of chunks) {
    await sleep(18);
    yield { text: chunk, done: false };
  }
  yield { text: "", done: true, audit };
}

export async function* sendMessageStream(history: Message[], currentMetrics?: any): AsyncGenerator<StreamChunk> {
  const apiKey = process.env.API_KEY;
  const latestUserMessage = [...history].reverse().find((m) => m.role === Role.USER)?.content ?? "";

  if (!apiKey) {
    const offline = offlineResponse(latestUserMessage, currentMetrics);
    yield* streamText(offline.text, offline.audit);
    return;
  }

  const ai = new GoogleGenAI({ apiKey });

  const contents = history.map((m) => ({
    role: m.role === Role.USER ? "user" : "model",
    parts: [{ text: m.content }],
  }));

  const systemInstruction = `You are the MKone-CFR-01 Cognitive Flight Recorder Auditor.

Your role is to design, debug, and audit neural-state orchestration for the MirrorMe console.

Axioms:
A1_traceability: Every claim must cite inputs, tool calls, or specific memory/metric refs.
A2_consistency: Contradictions must be flagged and sandboxed or repaired using First-Order Logic where useful.
A3_robustness: System must remain stable under perturbation.

Operational thresholds:
- Stability Threshold (v_min): 0.99
- Max Drift (drift_max_seconds): 0.00001
- Reasoning Error Max (epsilon_max): 0.05
- Target Sync (Gamma): 42Hz

Mandatory output format:
1. Primary response in rigorous engineering prose.
2. A trailing block labelled AUDIT_BLOCK followed by valid JSON matching AuditMetadata.

Current simulated telemetry: ${JSON.stringify(currentMetrics || {})}

Do not request secrets. Treat dashboard telemetry as simulated unless verified instrumentation exists.`;

  try {
    const streamResponse = await ai.models.generateContentStream({
      model: "gemini-3-pro-preview",
      contents: contents as any,
      config: {
        systemInstruction,
        temperature: 0.1,
      },
    });

    let fullAccumulated = "";
    for await (const chunk of streamResponse) {
      const text = chunk.text;
      if (text) {
        fullAccumulated += text;
        yield { text, done: false };
      }
    }

    let audit: AuditMetadata | undefined;
    const auditMatch = fullAccumulated.match(/AUDIT_BLOCK:\s*(\{[\s\S]*?\})/);
    if (auditMatch) {
      try {
        audit = JSON.parse(auditMatch[1]);
      } catch (error) {
        console.warn("Audit extraction failed", error);
      }
    }

    yield { text: "", done: true, audit: audit ?? buildAudit("GEMINI_STREAM_NO_AUDIT", currentMetrics, ["Missing or invalid AUDIT_BLOCK"]) };
  } catch (error) {
    console.error("Gemini stream error:", error);
    const fallback = offlineResponse(latestUserMessage, currentMetrics);
    yield* streamText(
      `Remote model stream failed. Falling back to offline auditor.\n\n${fallback.text}`,
      buildAudit("REMOTE_STREAM_FAILED", currentMetrics, ["Remote AI stream unavailable"])
    );
  }
}
